version: '3.8'

services:
  caughtwiki:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_NAME}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${PASSPHRASE_SALT}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
